### ISSUE TITLE
Allow to specify html element and not full screen

### ISSUE THREAD

**Issue by josepowera** [microsoft/mouselog.js#15]
It would be great to be able to specify html element that should have mouselog running on - for example we wan't to see only how user is going over specific form or html5 video.

Allow on run method to send aditional argument with Html element

```html
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/mouselog@latest/build/mouselog.js"></script>
<script>
    var myElement = document.getElementById("form1");
    mouselog.run({
        uploadEndpoint: "Your_Server_Url",
        websiteId: "Your_Website_Id",
        endpointType: "absolute",
        element: myelement
    });
</script>
```

**Comment by hsluoyz** [comment]
@kingiw I think we can consider this feature, any way to make it happen?

**Comment by kingiw** [comment]
Thanks for your inspiring suggestion. The implementation details of this feature is under discussion. I think this feature will be added in the coming versions.

**Comment by kingiw** [comment]
#19 PR is merged. Now you can specify HTML element in `config.scope` to let Mouselog agent listen and capture events in specific DOM instead of the whole screen.
