### ISSUE TITLE
Add A Contribution Guideline and A Description About the Project

### ISSUE THREAD

**Issue by ashu8912** [microsoft/mouselog.js#3]
The Project is missing a description and also a contribution guideline .

**Comment by hsluoyz** [comment]
Hi @ashu8912 , sorry for late response, as I didn't watch this repo before :)

We added the description here: https://github.com/microsoft/mouselog.js

We do not have a written version for contribution guideline. But basically we follow the GitHub work-flow: send issue, then send PR. Then we will review and merge PRs.
